version: 2

jobs:

  build:

    machine:
      # https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2

    steps:
      - checkout

      - restore_cache:
          keys:
            - my_cache

      - run: if [[ ! -d ~/data/ds114_test1 ]]; then wget -c -O ${HOME}/ds114_test1.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e54a326c613b01d7d3ed90" && mkdir -p ${HOME}/data && tar xf ${HOME}/ds114_test1.tar -C ${HOME}/data; fi
      - run: if [[ ! -d ~/data/ds114_test2 ]]; then wget -c -O ${HOME}/ds114_test2.tar "https://files.osf.io/v1/resources/9q7dv/providers/osfstorage/57e549f9b83f6901d457d162" && mkdir -p ${HOME}/data && tar xf ${HOME}/ds114_test2.tar -C ${HOME}/data; fi
      - run: if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
      - run: git describe --tags > version
      - run:
          command: docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
          no_output_timeout: 6h
      - run: mkdir -p ~/docker; docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
      - run: mkdir -p ${HOME}/outputs

      - save_cache:
          key: my_cache
          paths:
            - "~/docker"
            - "~/data"                 

      - run:
          command: docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs session --participant_label 01
          no_output_timeout: 6h
      - run:
          command: -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs1:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs group --participant_label 01 02
          no_output_timeout: 6h

  deployment:
  
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - run:
          command: if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker push bids/${CIRCLE_PROJECT_REPONAME}:latest; fi 
          no_output_timeout: 6h
      - run:
          command: if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker tag bids/${CIRCLE_PROJECT_REPONAME} bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG && docker push bids/${CIRCLE_PROJECT_REPONAME}:$CIRCLE_TAG; fi
          no_output_timeout: 6h


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deployment:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/


# VS Code Extension Version: 1.5.1
