---
name: test latest image

on:
  push:
    branches: ['*']
  schedule:
  - cron: 0 0 1 * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test_dataset_without_session:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tree

    - name: pull docker image
      run: docker pull bids/ndmg:latest

    - name: print version
      run: |
        docker run -t --rm --read-only \
        --tmpfs /tmp \
        --tmpfs /var/tmp \
            bids/ndmg:latest --version

        docker run -t --rm --read-only \
        --tmpfs /tmp \
        --tmpfs /var/tmp \
            bids/ndmg:latest --help

    - name: get data
      run: |
        wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
        bash get_data_from_osf.sh ds114_test1

    - name: prepare output dir
      run: |
        mkdir -p ${HOME}/outputs

    - name: participant 01
      run: |
        docker run -t --rm --read-only \
          -v ${HOME}/data/ds114_test1:/bids_dataset \
          -v ${HOME}/outputs:/outputs \
          --tmpfs /tmp \
          --tmpfs /var/tmp \
            bids/ndmg:latest \
              /bids_dataset /outputs session \
                --participant_label 01

    - name: check output
      run: tree ${HOME}/outputs

    - name: participant 02
      run: |
        docker run -t --rm --read-only \
          -v ${HOME}/data/ds114_test1:/bids_dataset \
          -v ${HOME}/outputs:/outputs \
          --tmpfs /tmp \
          --tmpfs /var/tmp \
            bids/ndmg:latest \
              /bids_dataset /outputs session \
                --participant_label 02

    - name: check output
      run: tree ${HOME}/outputs

    - name: group
      run: |
        docker run -t --rm --read-only \
        -v ${HOME}/data/ds114_test1:/bids_dataset \
        -v ${HOME}/outputs:/outputs \
        --tmpfs /tmp \
        --tmpfs /var/tmp \
          bids/ndmg:latest \
            /bids_dataset /outputs group \
              --participant_label 01 02
